server = {
  port: 8080,
  host: "0.0.0.0"
}

database = {
  path: "./target/db/quicksand.sqlite"
}

mail_fetcher = {
  enabled: false,
  period_seconds: 15
}

mail_sender = {
  enabled: false,
  period_seconds: 15
}

accounts = []

demo = {
  enabled: false,
  smtp_port: 4025,
  imap_port: 4143,
  seed_count: 273,

  account = {
    name: "Greenmail Test Account",
    imap_host: "localhost",
    imap_port: 4143,
    imap_username: "testuser",
    imap_password: "testpassword",
    smtp_host: "localhost",
    smtp_port: 4025,
    smtp_username: "testuser",
    smtp_password: "testpassword"
  }
}
